apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rbac-deployment
  labels:
    app: go-rbac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-rbac
  template:
    metadata:
      labels:
        app: go-rbac
    spec:
      containers:
      - name: go-rbac
        image: qinyuntasha/go-rbac
        ports:
        - containerPort: 8080