apiVersion: v1
kind: Service
metadata:
  name: go-rbac-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: go-rbac
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000